beer_list = ['Altbier',
'Amber ale',
'Barley wine',
'American-Style Barley Wine Ale',
'American Barleywine',
'Berliner Weisse',
'Bière de Garde',
'Bitter',
'Special or Best Bitter',
'Extra Special Bitter',
'Best Bitter',
'Strong Bitter',
'Blonde Ale',
'Belgian-Style Blonde Ale',
'Bock',
'Brown ale',
'American-Style Brown Ale',
'American Brown Ale',
'London Brown Ale (Historical)',
'California Common/Steam Beer',
'Cream Ale',
'Dortmunder Export',
'Doppelbock',
'Dunkel'
'European-Style Dark Lager',
'Dunkelweizen',
'Eisbock',
'Flanders red ale',
'Golden/Summer ale',
'Golden or Blonde Ale',
'Gose',
'Contemporary Gose',
'Gueuze',
'Hefeweizen',
'Helles',
'India pale ale',
'American-Style India Pale Ale',
'Session India Pale Ale',
'Imperial or Double India Pale Ale',
'English IPA',
'American IPA',
'Specialty IPA',
'Double IPA',
'Kölsch',
'Lambic',
'Belgian-Style Fruit Lambic',
'Fruit Lambic',
'Light ale',
'Maibock/Helles bock',
'Malt liquor',
'Mild',
'English-Style Dark Mild Ale',
'Oktoberfestbier/Märzenbier',
'German-Style Oktoberfest/Wiesn',
'Märzen',
'Old ale',
'Oud bruin',
'Pale ale',
'American-Style Pale Ale',
'American-Style Strong Pale Ale',
'Belgian-Style Pale Ale',
'Australian-Style Pale Ale',
'International-Style Pale Ale',
'Belgian Pale Ale',
'Pilsener/Pilsner/Pils',
'Bohemian-Style Pilsener',
'American-Style Pilsener',
'International-Style Pilsener',
'International Pale Lager',
'Czech Pale Lager',
'Czech Premium Pale Lager',
'German Pils',
'Porter',
'Robust Porter',
'American-Style Imperial Porter',
'Smoke Porter',
'Baltic-Style Porter',
'English Porter',
'American Porter',
'Pre-Prohibition Porter (Historical)',
'Red ale',
'American-Style Amber/Red Ale',
'Double Red Ale',
'Imperial Red Ale',
'Roggenbier',
'Saison',
'Specialty Saison',
'Scotch ale',
'Stout',
'Dry Stout[54]',
'Imperial Stout[54]',
'Oatmeal Stout',
'British-Style Imperial Stout',
'Classic Irish-Style Dry Stout',
'Export-Style Stout',
'American-Style Stout',
'American-Style Imperial Stout',
'Irish Extra Stout',
'Sweet Stout',
'Oatmeal Stout',
'Tropical Stout',
'Foreign Extra Stout',
'American Stout',
'Imperial Stout',
'Schwarzbier',
'Vienna lager',
'Witbier',
'Weissbier',
'German-Style Leichtes Weizen',
'South German-Style Bernsteinfarbenes Weizen',
'Weizenbock',
'Fruit beer',
'American-Style Fruit Beer',
'Fruit Wheat Beer',
'Belgian-Style Fruit Beer',
'Fruit Beer',
'Fruit and Spice Beer',
'Specialty Fruit Beer',
'Herb and spiced beer',
'Chili Pepper Beer',
'Chocolate or Cocoa Beer',
'Coffee Beer',
'Herb and Spice Beer',
'Spice, Herb, or Vegetable Beer',
'Autumn Seasonal Beer',
'Winter Seasonal Beer',
'Honey beer',
'Rye Beer',
'Smoked beer',
'Specialty Smoked Beer',
'Vegetable beer',
'Field Beer',
'Pumpkin Spice Beer',
'Pumpkin/Squash Beer',
'Spice, Herb, or Vegetable Beer',
'Wild beer',
'Brett Beer',
'Mixed-Culture Brett Beer',
'Wild Beer',
'Brett Beer',
'Mixed-Fermentation Sour Beer',
'Wild Specialty Beer',
'Wood-aged beer',
'Wood- and Barrel-Aged Pale to Amber Beer',
'Wood- and Barrel-Aged Dark Beer',
'Wood- and Barrel-Aged Strong Beer',
'Wood- and Barrel-Aged Sour Beer',
'Specialty Wood-Aged Beer',
'Lager',
'IPA',
'Indian Pale Ale',
'American Pale Ale'
]
